name: Upstream
on:
  schedule:
    - cron: "41 */6 * * *"
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  upstream:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git remote add upstream https://github.com/typst/citationberg.git
      - run: git fetch upstream
      - run: git switch upstream 2>/dev/null || git switch -c upstream
      - run: git reset --hard upstream/main
      - run: git push --force origin upstream
      - run: gh pr create --title "Upstream" --fill || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
